# Generated by Django 4.2.5 on 2023-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='amg/')),
            ],
            options={
                'verbose_name': 'RawImage',
                'verbose_name_plural': 'RawImages',
                'ordering': ('-pk',),
            },
        ),
    ]
